### ISSUE TITLE
not compatible with current version of vscode

### ISSUE THREAD

**Issue by muyuuuu** [OrangeX4/vscode-smart-ime#1]
as picture: 

![image](https://github.com/OrangeX4/vscode-smart-ime/assets/43681138/358f66d2-d002-46fa-ae17-4f294fa8d541)

**Comment by OrangeX4** [comment]
可以更新你的 vscode



---Original---
From: ***@***.***&gt;
Date: Mon, Oct 16, 2023 09:29 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [OrangeX4/vscode-smart-ime] not compatible with current version ofvscode (Issue #1)




 
as picture:
