### ISSUE TITLE
获取输入法的key失败，请检查是否正确设置了“ObtainIMCmd”。

### ISSUE THREAD

**Issue by LUORANCHENG** [OrangeX4/vscode-smart-ime#2]
获取输入法的key失败，请检查是否正确设置了“ObtainIMCmd”。

![2023-10-16_21-44](https://github.com/OrangeX4/vscode-smart-ime/assets/80999506/0462b040-f9a3-4215-bb42-de25e1d7562d)

**Comment by OrangeX4** [comment]
搜索插件 IME and cursor，然后按插件说明进行设置



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月16日(周一) 晚上9:46
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [OrangeX4/vscode-smart-ime] 获取输入法的key失败，请检查是否正确设置了“ObtainIMCmd”。 (Issue #2)




 
获取输入法的key失败，请检查是否正确设置了“ObtainIMCmd”。
