### ISSUE TITLE
手动切换输入法之后光标样式不会随之修改、光标在中文字符串中离开后不会自动切换为英文

### ISSUE THREAD

**Issue by bukkumaaku** [OrangeX4/vscode-smart-ime#3]
操作系统：Mac os 14
语言：PHP、Python
使用smart ime之后，手动切换输入法之后光标样式不会随之修改、光标在中文字符串中离开后不会自动切换为英文输入法（但是在中文注释离开后会自动更改为英文输入法）
![QQ20231017-153016-HD](https://github.com/OrangeX4/vscode-smart-ime/assets/76622967/6594c8f6-506f-4c8a-bff3-934400f8268a)

**Comment by OrangeX4** [comment]
# 手动切换输入法之后光标样式不会随之修改

请使用 `shift + space` 切换输入法，而不是使用系统自带的快捷键。搜索插件 [IME and cursor](https://marketplace.visualstudio.com/items?itemName=beishanyufu.ime-and-cursor) 查看更详细的说明。

# 光标在中文字符串中离开后不会自动切换为英文

并没有默认实现这个功能，不过你可以手动配置，参照 README 的说明，你可以将 `smart-ime.leaveScopesSwitchToEnglish` 设置项设置为 `comment,string` 来实现你要的效果。

**Comment by bukkumaaku** [comment]
感谢！已解决
