### ISSUE TITLE
我在安装扩展时出现了版本不兼职的问题

### ISSUE THREAD

**Issue by yinshaoqian** [OrangeX4/vscode-smart-ime#4]
[Window Title]
Visual Studio Code

[Content]
无法安装“orangex4.vscode-smart-ime”扩展，因为它与当前 Visual Studio Code 版本不兼容(版本 1.82.2)。

**Comment by OrangeX4** [comment]
升级你的 vscode 到最新版即可



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月18日(周三) 上午9:58
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [OrangeX4/vscode-smart-ime] 我在安装扩展时出现了版本不兼职的问题 (Issue #4)




 
[Window Title]
 Visual Studio Code
 
[Content]
 无法安装“orangex4.vscode-smart-ime”扩展，因为它与当前 Visual Studio Code 版本不兼容(版本 1.82.2)。
