### ISSUE TITLE
在字符串中，若从中文删除到英文前，不会自动切换为英文输入法，而从英文删除到中文前会自动切换为中文输入法

### ISSUE THREAD

**Issue by bukkumaaku** [OrangeX4/vscode-smart-ime#5]
操作系统：Mac OS 14
VsCode版本：1.83.1

问题：在字符串中，若从中文删除到英文前，不会自动切换为英文输入法，而从英文删除到中文前会自动切换为中文输入法，但是删到空格前面又会切换为英文输入法。

翻了一圈设置也没找着，另外在vscode中按command+shift+p，并没有找到 “Developer: Inspect Editor Tokens and Scopes”，不知是不是插件设置出错还是缺少什么插件。

![QQ20231018-104638-HD](https://github.com/OrangeX4/vscode-smart-ime/assets/76622967/aee40a5d-d857-46ab-9ff6-67cbe4a77d26)

**Comment by OrangeX4** [comment]
并没有实现识别到前面是英文字符便切换到英文输入法的逻辑，README 中也没说有这种功能，这是符合预期的。因为这种识别到英文字符则切换到输英文输入法的特性是十分耗电的，我觉得这种情形应该不太需要。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月18日(周三) 上午10:53
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [OrangeX4/vscode-smart-ime] 在字符串中，若从中文删除到英文前，不会自动切换为英文输入法，而从英文删除到中文前会自动切换为中文输入法 (Issue #5)




 
操作系统：Mac OS 14
 VsCode版本：1.83.1
 
问题：在字符串中，若从中文删除到英文前，不会自动切换为英文输入法，而从英文删除到中文前会自动切换为中文输入法，但是删到空格前面又会切换为英文输入法。
 
翻了一圈设置也没找着，另外在vscode中按command+shift+p，并没有找到 “Developer: Inspect Editor Tokens and Scopes”，不知是不是插件设置出错还是缺少什么插件。

**Comment by OrangeX4** [comment]
以及 `Developer: Inspect Editor Tokens and Scopes` 应该是 vscode 内置的功能，你找不到这个命令我也不清楚是为什么，也许可以搜索一下相关的问题？

**Comment by bukkumaaku** [comment]
好的，非常感谢解答！
