### ISSUE TITLE
使用Vim时输入法切换问题

### ISSUE THREAD

**Issue by stormckey** [OrangeX4/vscode-smart-ime#6]
现在 vim 下 normal mode 也会根据条件自动切换成中文输入法（比如把光标移动到中文字符上），但这个时候切换成中文完全没有任何必要，不知道这里的处理逻辑那个不能优化呢。

**Comment by OrangeX4** [comment]
感谢 issue，已更新，刚刚加入了一个在 Vim Normal 模式下禁用的设置。但是由于只是根据光标状态判断的（是否是块状光标），所以可能存在一定的 bug，之后如果能找到更好的解决方法我再看一下吧。
