### ISSUE TITLE
中文段落添加空格切换英文的规则

### ISSUE THREAD

**Issue by systemoutprintlnhelloworld** [OrangeX4/vscode-smart-ime#7]
添加规则,使得
如:
`中文: ` 这种场景下也可以执行双空格切换为英文,而避免切换输入法,满足复杂需求

**Comment by OrangeX4** [comment]
中文加单空格不是已经能切换英文了吗？



---原始邮件---
发件人: "hong ***@***.***&gt;
发送时间: 2023年11月28日(周二) 晚上8:09
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [OrangeX4/vscode-smart-ime] 添加双空格切换英文的规则 (Issue #7)




 
添加规则,使得
 如:
 中文:  这种场景下也可以执行双空格切换为英文,而避免切换输入法,满足复杂需求

**Comment by systemoutprintlnhelloworld** [comment]
你误会我意思了,我是说这种情况
`xtrue的意思是: true image,真实图像`
这句中 ture image这个英文文本之前是分号而不是中文,导致其无法实现空格后切换为英文

**Comment by OrangeX4** [comment]
感谢，之后考虑一下



---原始邮件---
发件人: "hong ***@***.***&gt;
发送时间: 2023年11月28日(周二) 晚上8:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [OrangeX4/vscode-smart-ime] 添加双空格切换英文的规则 (Issue #7)




 
你误会我意思了,我是说这种情况
 xtrue的意思是: true image,真实图像
 这句中 ture image这个英文文本之前是分号而不是中文,导致其无法实现空格后切换为英文

**Comment by systemoutprintlnhelloworld** [comment]
不客气
