### ISSUE TITLE
搜狗输入自动切换成英文的问题

### ISSUE THREAD

**Issue by Rainboylvx** [OrangeX4/vscode-smart-ime#8]
我使用搜狗五笔输入时,会自动切换成英文,然后又立刻切换成中文,因为这个输入法打一个字符会添加一个空格,于是自动切换成英文,
rime输入法同样 ,自带的微软五笔不会这样.具体 看视频

https://github.com/OrangeX4/vscode-smart-ime/assets/8732377/b4681bcb-19bf-446e-b2fe-35ac4b99d667

**Comment by OrangeX4** [comment]
你可以在配置里面把你不喜欢的功能关闭，例如双空格切换成中文的功能关掉
