### ISSUE TITLE
插件在vscode中安装但是在window其他地方依旧起作用

### ISSUE THREAD

**Issue by lintu1** [OrangeX4/vscode-smart-ime#9]
插件在vsoced中安装成功，但是在切换的微信聊天框以及excel等文档中依旧生效且无法切换输入法

**Comment by OrangeX4** [comment]
使用 win+space 键就可以切换回来。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月22日(周一) 下午3:15
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [OrangeX4/vscode-smart-ime] 插件在vscode中安装但是在window其他地方依旧起作用 (Issue #9)




 
插件在vsoced中安装成功，但是在切换的微信聊天框以及excel等文档中依旧生效且无法切换输入法

**Comment by lintu1** [comment]
能否配置，只在vscode中生效

**Comment by OrangeX4** [comment]
这个没什么办法，这是 vscode 和 Windows 自身的限制。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月22日(周一) 下午4:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [OrangeX4/vscode-smart-ime] 插件在vscode中安装但是在window其他地方依旧起作用 (Issue #9)




 
能否配置，只在vscode中生效
